<?php

/**
 * @file
 * Module help file for the Random Pokemon module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function random_pokemon_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.random_pokemon':
      return t('
        <div class="container">
          <div class="row">
            <div class="col-12">
              <h2>Random Pokemon</h2>
              <p>
                This module provides a simple way to generate a random Pokemon.
              </p>
              <p>
                <strong>Random Pokemon</strong>
              </p>
          </div>
        </div>
      ');
  }
}
